requires = [
    "tox>=4.24.1",
    "tox-uv>=1.20.1",
]
env_list = [
    "3.10",
    "3.11",
    "3.12",
]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8",
]
commands = [
    ["pytest"],
]
