name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} and Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install uv on Non-Windows
      - name: Install uv on Non-Windows
        if: runner.os != 'Windows'
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # Install uv on Windows
      - name: Install uv on Windows
        if: runner.os == 'Windows'
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: false  # Cache is causing issues on Windows due to access permissions during pruning

      # Install project dependencies, including dev dependencies
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # Run tests using pytest
      - name: Run tests
        run: uv run pytest
